// src/controllers/discountCodeController.js
const discountCodeService = require('../services/discountCodeService');

// -----------------------------------------------------------------------------
// POST /discount-codes/generate
// Generates a new referral code for the authenticated user.
// Body: { recipient_note?: string }
// -----------------------------------------------------------------------------
const generateReferralCode = async (req, res) => {
  try {
    const { recipient_note } = req.body;
    const firstName          = req.user.first_name || req.user.email?.split('@')[0];

    const code = await discountCodeService.generateReferralCode(
      req.user.id,
      firstName,
      recipient_note || null
    );

    return res.status(201).json({ success: true, data: code });
  } catch (error) {
    console.error('Generate referral code error:', error);
    return res.status(500).json({ success: false, error: 'Failed to generate referral code' });
  }
};

// -----------------------------------------------------------------------------
// GET /discount-codes
// Returns all referral codes generated by the authenticated user.
// -----------------------------------------------------------------------------
const getUserCodes = async (req, res) => {
  try {
    const codes = await discountCodeService.getUserCodes(req.user.id);
    return res.status(200).json({ success: true, data: codes });
  } catch (error) {
    console.error('Get user codes error:', error);
    return res.status(500).json({ success: false, error: 'Failed to fetch codes' });
  }
};

// -----------------------------------------------------------------------------
// POST /discount-codes/validate
// Validates a code without applying it — used for the sidebar check before apply.
// Body: { code: string }
// -----------------------------------------------------------------------------
const validateCode = async (req, res) => {
  try {
    const { code } = req.body;

    if (!code?.trim()) {
      return res.status(400).json({ success: false, error: 'Code is required' });
    }

    const result = await discountCodeService.validateCode(code, req.user.id);
    return res.status(200).json({ success: true, data: result });
  } catch (error) {
    console.error('Validate code error:', error);
    // Surface specific validation errors cleanly to the frontend
    const userFacingErrors = [
      'Code not found',
      'You cannot use your own referral code',
      'This code has already been used',
      'This code has expired',
      'Referral codes are only valid on your first booking',
    ];
    if (userFacingErrors.includes(error.message)) {
      return res.status(422).json({ success: false, error: error.message });
    }
    return res.status(500).json({ success: false, error: 'Failed to validate code' });
  }
};

// -----------------------------------------------------------------------------
// POST /bookings/:bookingId/apply-discount
// Applies a validated discount code to a booking.
// Body: { code: string }
// -----------------------------------------------------------------------------
const applyCode = async (req, res) => {
  try {
    const { bookingId } = req.params;
    const { code }      = req.body;

    if (!code?.trim()) {
      return res.status(400).json({ success: false, error: 'Code is required' });
    }

    const result = await discountCodeService.applyCode(code, req.user.id, bookingId);
    return res.status(200).json({ success: true, data: result });
  } catch (error) {
    console.error('Apply code error:', error);
    const userFacingErrors = [
      'Code not found',
      'You cannot use your own referral code',
      'This code has already been used',
      'This code has expired',
      'Referral codes are only valid on your first booking',
      'Booking is already fully discounted',
      'Invoice not found',
    ];
    if (userFacingErrors.includes(error.message)) {
      return res.status(422).json({ success: false, error: error.message });
    }
    return res.status(500).json({ success: false, error: 'Failed to apply code' });
  }
};

// -----------------------------------------------------------------------------
// DELETE /bookings/:bookingId/apply-discount
// Removes a discount code from a booking before payment.
// -----------------------------------------------------------------------------
const removeCode = async (req, res) => {
  try {
    const { bookingId } = req.params;
    const result        = await discountCodeService.removeCode(bookingId, req.user.id);
    return res.status(200).json({ success: true, data: result });
  } catch (error) {
    console.error('Remove code error:', error);
    return res.status(500).json({ success: false, error: 'Failed to remove code' });
  }
};

// -----------------------------------------------------------------------------
// POST /admin/discount-codes
// Admin only — creates a promo code.
// Body: { code, discount_amount, expires_at?, notes? }
// -----------------------------------------------------------------------------
const createPromoCode = async (req, res) => {
  try {
    const { code, discount_amount, expires_at, notes } = req.body;

    if (!code || !discount_amount) {
      return res.status(400).json({ success: false, error: 'Code and discount amount are required' });
    }

    const result = await discountCodeService.createPromoCode(req.user.id, {
      code,
      discountAmount: Number(discount_amount),
      expiresAt:      expires_at || null,
      notes:          notes || null,
    });

    return res.status(201).json({ success: true, data: result });
  } catch (error) {
    console.error('Create promo code error:', error);
    if (error.message?.includes('unique')) {
      return res.status(409).json({ success: false, error: 'A code with that name already exists' });
    }
    return res.status(500).json({ success: false, error: 'Failed to create promo code' });
  }
};

module.exports = {
  generateReferralCode,
  getUserCodes,
  validateCode,
  applyCode,
  removeCode,
  createPromoCode,
};